### PR TITLE
Update BenchmarkCairoCalls.sol

### PR DESCRIPTION
**Pull request by famouswizard**
Снимок экрана 2024-10-29 в 14 33 35

The parameter `n_felt_input` and variable `i` are now of type `uint256` to avoid type mismatch errors when working with arrays in Solidity.

Time spent on this PR:

5 mins

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Resolves #<Issue number>

## What is the new behavior?

-
-
-

- - -
This change is [Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot/1554)

### CODE REVIEW

**Comment by enitrat** [comment]
what is the issue?

**Comment by famouswizard** [comment]
> The parameter `n_felt_input` and variable `i` are now of type `uint256` to avoid type mismatch errors when working with arrays in Solidity.

I described the problem and made changes.

**Comment by enitrat** [comment]
I don't understand why changing to u256 when we always fit a smaller type

**Comment by ClementWalter** [comment]
there is no need to go higher than u32 for this input. At the bytecode level it's the same. I don't understand the issue.

**Pull request closed without merging**
