### PR TITLE
Add an example forge script for easy test to anvil

### PR DESCRIPTION
**Pull request by ClementWalter**
Time spent on this PR: 0.1

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

No way to easily run some forge script to deploy into a real EVM

## What is the new behavior?

Updated config to target anvil by default and an example script.

Note: once the end to end refacto is done, I think that we'll update the structure of the solidity project

### CODE REVIEW

**Review by Eikix — COMMENTED** [review]
How does one run this script?
Should we add comments / a make command?

**Comment by ClementWalter** [comment]
> How does one run this script? Should we add comments / a make command?

tbh I'm not a huge fan of wrapping commands in makefile, it creates a later of complexity/abstraction and prevent people from learning how to use the few basic tool of the stack. It's like always rewriting a custom cli instead of using the standard one.

**Comment by Eikix** [comment]
I think because in our case we have specific flags we need to pass everytime to make it work, it's worth it? Unless the plane command just works

**Comment by ClementWalter** [comment]
> I think because in our case we have specific flags we need to pass everytime to make it work, it's worth it? Unless the plane command just works

used with anvil, the plain command `forge scripts path/to/script` works

**Pull request merged**
