### PR TITLE
feat: return gas_used in eth_call and eth_send_transaction

### PR DESCRIPTION
**Pull request by enitrat**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Resolves: #870

## What is the new behavior?

- Return gas_used in eth_send_transaction and eth_call
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

- - -
This change is [Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot/876)

### CODE REVIEW

**Review by ClementWalter — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot/876)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Review by ClementWalter — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot/876)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Review by ClementWalter — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot/876)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Review by enitrat — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot/876#-:-NoBbznDE00ZKI-2AQvG:bnfp4nl)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @ClementWalter)

**Review by ClementWalter — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot/876)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Review by ClementWalter — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot/876)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @enitrat)

**Pull request merged**
