### PR TITLE
chore: add solidity formatter

### LINKED ISSUE #1244: style: add a solidity formatter
## Feature Request
Add a forge fmt (or solhint) in trunk to standardize the formatting of solidity files

### PR DESCRIPTION
**Pull request by enitrat**
Time spent on this PR: 0.5h

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Resolves #1244

## What is the new behavior?

-
-
-

- - -
This change is [Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot/1247)

### CODE REVIEW

**Comment by obatirou** [comment]
Realizing that some external contracts are copy/pasted for tests in the src directory, `solmate` and `uniswapV2` among others, and this PR change their code. It should be avoided if possible.
A new issue should be created to import those a dependencies in forge to avoid formatting those contracts or introducing regressions accidentally. Maybe even do this before introducing the formatter ?
Not sure what are the implication of this and what impact it would have on how the tests are constructed with python if imported with forge.

One solution in the meantime to avoid applying the forge fmt to them is to use the [ignore](https://book.getfoundry.sh/reference/config/formatter#ignore) for forge fmt.
If those contracts are kept copy / paste in the end, a commit hash of original repo should be associated to track them.

**Comment by ClementWalter** [comment]
@enitrat should we just ignore or upgrade to have these files as submodule?
I suggest
1. ignore and merge this
2. create an issue to have submodules

**Comment by enitrat** [comment]
@obatirou did you find any info on why uint -> uint256 ended up making the test fail?

**Comment by obatirou** [comment]
> @obatirou did you find any info on why uint -> uint256 ended up making the test fail?

Unfortunately no, will try again this week

**Review by obatirou — APPROVED** [review]

**Review by ClementWalter — APPROVED** [review]

**Pull request merged**
